FEAT: add support for notebooks with Julia kernel (#174)
* DOC: add Julia and IJulia kernel installation instructions
* DOC: add TR-019 Jupyter notebook with Jupyter kernel
* DX: activate cSpell for Julia files
* DX: move `--nbmake-timeout` option to `pytest.ini`
* DX: recommend VSCode Julia extension
* DX: skip Julia notebook with `nbmake`
* MAINT: remove redundant workflow step names

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -31,4 +31,17 @@ jobs:
           pip install -c .constraints/py3.8.txt .[test]
       - name: Run notebooks with pytest (diff only)
         if: steps.diff.outputs.modified-notebooks != ''
-        run: pytest --nbmake --nbmake-timeout=1200 $(cat diff.txt)
+        run: |
+          function run-nbmake() {
+            set +e
+            pytest --nbmake $(cat diff.txt)
+            error_code=$?
+            set -e
+            echo "Pytest returned error code $error_code"
+            case $error_code in
+              0|5) return 0;;
+              *) return $error_code;;
+            esac
+          }
+          run-nbmake
+        # cspell:ignore esac
diff --git a/.github/workflows/notebooks.yml b/.github/workflows/notebooks.yml
--- a/.github/workflows/notebooks.yml
+++ b/.github/workflows/notebooks.yml
@@ -22,4 +22,16 @@ jobs:
           sudo apt-get -y install graphviz
           pip install -c .constraints/py3.8.txt .[test]
       - run: |
-          pytest --nbmake --nbmake-timeout=1200 ${{ github.event.inputs.notebook-selector }}
+          function run-nbmake() {
+            set +e
+            pytest --nbmake ${{ github.event.inputs.notebook-selector }}
+            error_code=$?
+            set -e
+            echo "Pytest returned error code $error_code"
+            case $error_code in
+              0|5) return 0;;
+              *) return $error_code;;
+            esac
+          }
+          run-nbmake
+        # cspell:ignore esac
